name: Gravity
version: '${project.version}'
main: me.gravity.gravity.Gravity
api-version: 1.19
commands:
  ResetArrows:
    description: deletes all arrows
  SpawnVehicle:
    description: places the user on an arrow
